# Generated by Django 3.2.4 on 2021-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0002_remove_streetaddress_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetaddress',
            name='unit_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
