# Generated by Django 3.2.4 on 2021-06-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0003_alter_streetaddress_unit_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_of_title', models.CharField(max_length=100, null=True)),
                ('legal_desc', models.CharField(max_length=1000, null=True)),
                ('address_head', models.CharField(max_length=100, null=True)),
                ('address_subhead', models.CharField(max_length=100, null=True)),
                ('capital_value', models.CharField(max_length=100, null=True)),
                ('value_improv', models.CharField(max_length=100, null=True)),
                ('valuation_number', models.CharField(max_length=100, null=True)),
                ('rate_year', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('description_of_improvements', models.CharField(max_length=1000, null=True)),
                ('local_board', models.CharField(max_length=100, null=True)),
                ('property_zone', models.CharField(max_length=100, null=True)),
                ('bedrooms', models.CharField(max_length=100, null=True)),
                ('street_park', models.CharField(max_length=100, null=True)),
                ('garage_freestanding', models.CharField(max_length=100, null=True)),
                ('garage_underMain', models.CharField(max_length=100, null=True)),
                ('full_address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
