# Generated by Django 3.2.4 on 2021-06-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0004_propertyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrate',
            name='Land_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertyrate',
            name='rates_assessment_number',
            field=models.IntegerField(null=True),
        ),
    ]
