# Generated by Django 3.2.4 on 2021-06-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0006_rename_land_value_propertyrate_land_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrate',
            name='rates_assessment_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
