# Generated by Django 3.2.4 on 2021-06-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0007_alter_propertyrate_rates_assessment_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyRate',
        ),
    ]
