# Generated by Django 3.2.4 on 2021-06-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0008_delete_propertyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_no', models.CharField(db_index=True, max_length=100, null=True)),
                ('full_address', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('suburb', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
