# Generated by Django 3.2.4 on 2021-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0009_addresstitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstitle',
            name='address',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='addresstitle',
            name='full_address',
            field=models.CharField(max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='addresstitle',
            name='title_no',
            field=models.CharField(db_index=True, max_length=191, null=True),
        ),
    ]
