# Generated by Django 3.2.4 on 2021-06-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0010_auto_20210626_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTitleMortgageOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_no', models.CharField(db_index=True, max_length=191, null=True)),
                ('encumbrancees', models.CharField(db_index=True, max_length=191, null=True)),
                ('instrument_lodged_datetime', models.DateTimeField(null=True)),
                ('instrument_type', models.CharField(max_length=191, null=True)),
                ('full_address', models.CharField(max_length=191, null=True)),
                ('address', models.CharField(db_index=True, max_length=191, null=True)),
                ('suburb', models.CharField(max_length=191, null=True)),
                ('estate_description', models.CharField(max_length=1000, null=True)),
                ('owners', models.CharField(max_length=10000, null=True)),
                ('issue_date', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=191, null=True)),
                ('land_district', models.CharField(max_length=191, null=True)),
            ],
        ),
    ]
