# Generated by Django 3.2.4 on 2021-06-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0011_addresstitlemortgageowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstitlemortgageowner',
            name='encumbrancees',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
