# Generated by Django 3.2.4 on 2021-06-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0012_alter_addresstitlemortgageowner_encumbrancees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstitlemortgageowner',
            name='estate_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
