# Generated by Django 3.2.4 on 2021-06-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0013_alter_addresstitlemortgageowner_estate_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerTitleAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_no', models.CharField(db_index=True, max_length=191, null=True)),
                ('land_district', models.CharField(max_length=191, null=True)),
                ('issue_date', models.DateTimeField(null=True)),
                ('owners', models.CharField(db_index=True, max_length=191, null=True)),
                ('full_address', models.CharField(max_length=191, null=True)),
                ('address', models.CharField(db_index=True, max_length=191, null=True)),
            ],
        ),
    ]
