# Generated by Django 3.2.5 on 2021-07-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimensions', '0015_rename_owners_ownertitleaddress_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownertitleaddress',
            name='instrument_lodged_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
