version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/var/www/html/DataWarehouse/frontend/static
    env_file:
      - DataWarehouse/DataWarehouse/parameter.py
    build:
      context: .
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn


volumes:
  static: