# Generated by Django 3.2.4 on 2021-06-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleOwner', '0002_alter_titleowner_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleOwnerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_no', models.CharField(max_length=100)),
                ('land_district', models.CharField(max_length=100, null=True)),
                ('issue_date', models.DateTimeField(null=True)),
                ('owners', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
