# Generated by Django 3.2.5 on 2021-07-03 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_request_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 16, 39, 26, 410942)),
        ),
    ]
