# Generated by Django 3.2.5 on 2021-07-03 08:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0003_alter_userprofile_last_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_request_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 3, 20, 48, 27, 394163)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
