# Generated by Django 3.2.5 on 2021-07-04 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_auto_20210703_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_request_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 19, 12, 11, 92969)),
        ),
    ]
