# Generated by Django 3.2.5 on 2021-07-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_alter_userprofile_last_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
