# Generated by Django 3.2.4 on 2021-06-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitleMortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_no', models.CharField(max_length=100)),
                ('land_district', models.CharField(max_length=100)),
                ('memorial_text', models.TextField()),
                ('current', models.CharField(max_length=100)),
                ('instrument_number', models.CharField(max_length=100)),
                ('instrument_lodged_datetime', models.DateTimeField()),
                ('instrument_type', models.CharField(max_length=100)),
                ('encumbrancees', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
