# Generated by Django 3.2.4 on 2021-06-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titleMortgage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemortgage',
            name='current',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='titlemortgage',
            name='instrument_lodged_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='titlemortgage',
            name='instrument_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='titlemortgage',
            name='instrument_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='titlemortgage',
            name='memorial_text',
            field=models.TextField(null=True),
        ),
    ]
